export interface WeatherConditionInfo {
  code: number;
  label: string;
  category: 'clear' | 'partly-cloudy' | 'cloudy' | 'fog' | 'drizzle' | 'rain' | 'snow' | 'thunderstorm';
  icon: string; // Lucide icon identifier
  nightIcon: string;
  badgeClass: string;
  bgGradient: string;
  cardGlow: string;
  description: string;
}

export const WMO_WEATHER_MAP: Record<number, WeatherConditionInfo> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    category: 'clear',
    icon: 'Sun',
    nightIcon: 'Moon',
    badgeClass: 'text-amber-300 border-amber-500/30 bg-amber-500/10',
    bgGradient: 'from-amber-500/20 via-sky-500/10 to-transparent',
    cardGlow: 'rgba(245, 158, 11, 0.15)',
    description: 'Cloudless, clear conditions with unobstructed visibility.',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    category: 'partly-cloudy',
    icon: 'SunDim',
    nightIcon: 'MoonStar',
    badgeClass: 'text-amber-200 border-amber-400/30 bg-amber-400/10',
    bgGradient: 'from-amber-400/20 via-sky-500/10 to-transparent',
    cardGlow: 'rgba(251, 191, 36, 0.12)',
    description: 'Mostly sunny with scattered faint clouds.',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    category: 'partly-cloudy',
    icon: 'CloudSun',
    nightIcon: 'CloudMoon',
    badgeClass: 'text-sky-300 border-sky-500/30 bg-sky-500/10',
    bgGradient: 'from-sky-500/20 via-blue-600/10 to-transparent',
    cardGlow: 'rgba(56, 189, 248, 0.12)',
    description: 'Sun and clouds interchanging through the day.',
  },
  3: {
    code: 3,
    label: 'Overcast',
    category: 'cloudy',
    icon: 'Cloud',
    nightIcon: 'Cloud',
    badgeClass: 'text-slate-300 border-slate-500/30 bg-slate-500/10',
    bgGradient: 'from-slate-600/25 via-slate-800/15 to-transparent',
    cardGlow: 'rgba(148, 163, 184, 0.1)',
    description: 'Thick, continuous cloud cover with muted light.',
  },
  45: {
    code: 45,
    label: 'Fog',
    category: 'fog',
    icon: 'CloudFog',
    nightIcon: 'CloudFog',
    badgeClass: 'text-slate-300 border-slate-400/30 bg-slate-500/10',
    bgGradient: 'from-slate-500/20 via-zinc-700/15 to-transparent',
    cardGlow: 'rgba(203, 213, 225, 0.1)',
    description: 'Dense low-altitude fog; reduced visibility on roads.',
  },
  48: {
    code: 48,
    label: 'Depositing Rime Fog',
    category: 'fog',
    icon: 'CloudFog',
    nightIcon: 'CloudFog',
    badgeClass: 'text-teal-300 border-teal-500/30 bg-teal-500/10',
    bgGradient: 'from-teal-600/20 via-slate-700/15 to-transparent',
    cardGlow: 'rgba(45, 212, 191, 0.1)',
    description: 'Freezing fog coating surfaces with ice crystals.',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    category: 'drizzle',
    icon: 'CloudDrizzle',
    nightIcon: 'CloudDrizzle',
    badgeClass: 'text-cyan-300 border-cyan-500/30 bg-cyan-500/10',
    bgGradient: 'from-cyan-600/20 via-blue-800/15 to-transparent',
    cardGlow: 'rgba(6, 182, 212, 0.12)',
    description: 'Fine, gentle misty raindrops.',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    category: 'drizzle',
    icon: 'CloudDrizzle',
    nightIcon: 'CloudDrizzle',
    badgeClass: 'text-cyan-300 border-cyan-500/30 bg-cyan-500/10',
    bgGradient: 'from-cyan-600/25 via-blue-800/15 to-transparent',
    cardGlow: 'rgba(6, 182, 212, 0.14)',
    description: 'Steady fine mist; damp ground conditions.',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    category: 'drizzle',
    icon: 'CloudDrizzle',
    nightIcon: 'CloudDrizzle',
    badgeClass: 'text-cyan-200 border-cyan-400/30 bg-cyan-400/15',
    bgGradient: 'from-cyan-700/25 via-blue-800/15 to-transparent',
    cardGlow: 'rgba(6, 182, 212, 0.15)',
    description: 'Heavy continuous drizzle; water-resistant layer recommended.',
  },
  56: {
    code: 56,
    label: 'Light Freezing Drizzle',
    category: 'drizzle',
    icon: 'CloudSnow',
    nightIcon: 'CloudSnow',
    badgeClass: 'text-sky-200 border-sky-400/30 bg-sky-400/15',
    bgGradient: 'from-sky-700/25 via-slate-800/20 to-transparent',
    cardGlow: 'rgba(56, 189, 248, 0.15)',
    description: 'Sub-freezing mist creating slick patches on walkways.',
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    category: 'drizzle',
    icon: 'CloudSnow',
    nightIcon: 'CloudSnow',
    badgeClass: 'text-sky-200 border-sky-400/30 bg-sky-400/15',
    bgGradient: 'from-sky-700/30 via-slate-800/25 to-transparent',
    cardGlow: 'rgba(56, 189, 248, 0.18)',
    description: 'Heavy freezing drizzle causing icy surfaces.',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    category: 'rain',
    icon: 'CloudRain',
    nightIcon: 'CloudRain',
    badgeClass: 'text-blue-300 border-blue-500/30 bg-blue-500/10',
    bgGradient: 'from-blue-600/20 via-sky-800/15 to-transparent',
    cardGlow: 'rgba(59, 130, 246, 0.12)',
    description: 'Intermittent light rain showers; umbrella recommended.',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    category: 'rain',
    icon: 'CloudRain',
    nightIcon: 'CloudRain',
    badgeClass: 'text-blue-200 border-blue-400/30 bg-blue-500/15',
    bgGradient: 'from-blue-600/30 via-indigo-900/20 to-transparent',
    cardGlow: 'rgba(59, 130, 246, 0.18)',
    description: 'Steady soaking rainfall; waterproof gear advised.',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    category: 'rain',
    icon: 'CloudRain',
    nightIcon: 'CloudRain',
    badgeClass: 'text-indigo-200 border-indigo-400/40 bg-indigo-500/20',
    bgGradient: 'from-blue-700/35 via-indigo-950/30 to-transparent',
    cardGlow: 'rgba(79, 70, 229, 0.22)',
    description: 'Intense downpour; standing water on roads.',
  },
  66: {
    code: 66,
    label: 'Light Freezing Rain',
    category: 'rain',
    icon: 'CloudSnow',
    nightIcon: 'CloudSnow',
    badgeClass: 'text-sky-300 border-sky-400/30 bg-sky-500/15',
    bgGradient: 'from-sky-700/30 via-slate-900/20 to-transparent',
    cardGlow: 'rgba(56, 189, 248, 0.18)',
    description: 'Rain drops freezing on contact, slippery roads.',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    category: 'rain',
    icon: 'CloudSnow',
    nightIcon: 'CloudSnow',
    badgeClass: 'text-sky-100 border-sky-300/40 bg-sky-500/25',
    bgGradient: 'from-sky-800/40 via-slate-900/30 to-transparent',
    cardGlow: 'rgba(56, 189, 248, 0.25)',
    description: 'Severe freezing rain; treacherous black ice conditions.',
  },
  71: {
    code: 71,
    label: 'Slight Snowfall',
    category: 'snow',
    icon: 'Snowflake',
    nightIcon: 'Snowflake',
    badgeClass: 'text-cyan-200 border-cyan-300/30 bg-cyan-400/15',
    bgGradient: 'from-cyan-600/20 via-slate-800/20 to-transparent',
    cardGlow: 'rgba(103, 232, 249, 0.15)',
    description: 'Gentle flurries with light snow accumulation.',
  },
  73: {
    code: 73,
    label: 'Moderate Snowfall',
    category: 'snow',
    icon: 'Snowflake',
    nightIcon: 'Snowflake',
    badgeClass: 'text-cyan-100 border-cyan-300/40 bg-cyan-400/20',
    bgGradient: 'from-cyan-600/30 via-slate-800/25 to-transparent',
    cardGlow: 'rgba(103, 232, 249, 0.2)',
    description: 'Steady snowfall accumulating on roads and sidewalks.',
  },
  75: {
    code: 75,
    label: 'Heavy Snowfall',
    category: 'snow',
    icon: 'Snowflake',
    nightIcon: 'Snowflake',
    badgeClass: 'text-white border-white/40 bg-white/15',
    bgGradient: 'from-cyan-500/35 via-slate-800/30 to-transparent',
    cardGlow: 'rgba(255, 255, 255, 0.22)',
    description: 'Heavy drifting snow; reduced travel speed necessary.',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    category: 'snow',
    icon: 'Snowflake',
    nightIcon: 'Snowflake',
    badgeClass: 'text-cyan-200 border-cyan-400/30 bg-cyan-500/15',
    bgGradient: 'from-cyan-600/20 via-slate-800/20 to-transparent',
    cardGlow: 'rgba(103, 232, 249, 0.15)',
    description: 'Small opaque ice grains falling from stratus clouds.',
  },
  80: {
    code: 80,
    label: 'Slight Showers',
    category: 'rain',
    icon: 'CloudRain',
    nightIcon: 'CloudRain',
    badgeClass: 'text-blue-300 border-blue-500/30 bg-blue-500/10',
    bgGradient: 'from-blue-600/20 via-sky-800/15 to-transparent',
    cardGlow: 'rgba(59, 130, 246, 0.12)',
    description: 'Brief passing rain showers between dry breaks.',
  },
  81: {
    code: 81,
    label: 'Moderate Showers',
    category: 'rain',
    icon: 'CloudRain',
    nightIcon: 'CloudRain',
    badgeClass: 'text-blue-200 border-blue-400/30 bg-blue-500/15',
    bgGradient: 'from-blue-600/25 via-indigo-900/20 to-transparent',
    cardGlow: 'rgba(59, 130, 246, 0.16)',
    description: 'Periodic heavy bursts of rain.',
  },
  82: {
    code: 82,
    label: 'Violent Showers',
    category: 'rain',
    icon: 'CloudRain',
    nightIcon: 'CloudRain',
    badgeClass: 'text-indigo-200 border-indigo-400/40 bg-indigo-500/20',
    bgGradient: 'from-indigo-600/35 via-slate-900/30 to-transparent',
    cardGlow: 'rgba(99, 102, 241, 0.22)',
    description: 'Severe sudden rain bursts; rapid runoff.',
  },
  85: {
    code: 85,
    label: 'Slight Snow Showers',
    category: 'snow',
    icon: 'Snowflake',
    nightIcon: 'Snowflake',
    badgeClass: 'text-cyan-200 border-cyan-400/30 bg-cyan-400/15',
    bgGradient: 'from-cyan-600/25 via-slate-800/20 to-transparent',
    cardGlow: 'rgba(103, 232, 249, 0.16)',
    description: 'Occasional light snow squalls.',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    category: 'snow',
    icon: 'Snowflake',
    nightIcon: 'Snowflake',
    badgeClass: 'text-white border-white/40 bg-white/15',
    bgGradient: 'from-cyan-500/35 via-slate-900/30 to-transparent',
    cardGlow: 'rgba(255, 255, 255, 0.2)',
    description: 'Frequent heavy snow squalls; low visibility.',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    category: 'thunderstorm',
    icon: 'CloudLightning',
    nightIcon: 'CloudLightning',
    badgeClass: 'text-amber-200 border-amber-500/40 bg-amber-500/20',
    bgGradient: 'from-amber-600/25 via-purple-950/30 to-transparent',
    cardGlow: 'rgba(245, 158, 11, 0.2)',
    description: 'Lightning activity with gusty winds and rain.',
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Hail',
    category: 'thunderstorm',
    icon: 'CloudLightning',
    nightIcon: 'CloudLightning',
    badgeClass: 'text-amber-300 border-amber-400/50 bg-amber-500/25',
    bgGradient: 'from-purple-700/35 via-amber-900/25 to-transparent',
    cardGlow: 'rgba(217, 119, 6, 0.25)',
    description: 'Severe electrical storm with small hail stones.',
  },
  99: {
    code: 99,
    label: 'Heavy Hail Thunderstorm',
    category: 'thunderstorm',
    icon: 'CloudLightning',
    nightIcon: 'CloudLightning',
    badgeClass: 'text-rose-200 border-rose-400/50 bg-rose-500/25',
    bgGradient: 'from-rose-700/35 via-purple-950/35 to-transparent',
    cardGlow: 'rgba(244, 63, 94, 0.28)',
    description: 'Severe storm with damaging hail; seek indoor shelter.',
  },
};

export function getWeatherCondition(code: number, isDay: boolean = true): WeatherConditionInfo {
  const match = WMO_WEATHER_MAP[code];
  if (match) {
    return {
      ...match,
      icon: isDay ? match.icon : match.nightIcon,
    };
  }
  // Fallback for unexpected code
  return {
    code,
    label: 'Variable Clouds',
    category: 'partly-cloudy',
    icon: isDay ? 'CloudSun' : 'CloudMoon',
    nightIcon: 'CloudMoon',
    badgeClass: 'text-slate-300 border-slate-500/30 bg-slate-500/10',
    bgGradient: 'from-slate-600/20 via-slate-800/10 to-transparent',
    cardGlow: 'rgba(148, 163, 184, 0.1)',
    description: 'Typical mixed atmospheric conditions.',
  };
}
